name: poc-arrow
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev
- clangxx
- cmake
- llvmdev
- lld
- meson
- ninja
- pkg-config
# run
- arrow-cpp 10.*
- arrow-c-glib 10.*
- cli11
- glog
# dev
- nodejs
- pre-commit
- cmake-format
- cppcheck
- jupyterlab
- xeus-cling
- pip
- pip:
  - makim
  - jupyter-c-kernel
